version: '3.7'
services:
  daemon:
    hostname: daemon
    image: quay.io/parkervcp/pterodactyl-daemon:latest
    ports:
      - "8080:8080"
      - "2022:2022"
    tty: true
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/srv/daemon/config/:/srv/daemon/config/"
      - "/srv/daemon-data/:/srv/daemon-data/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl"
